from pathlib import Path
path = Path(__file__).resolve().parents[1] / 'tests' / 'test_integrity_key_portability.py'
text = path.read_text(encoding='utf-8')
old = "    def test_legacy_metadata_migration_validates_hmac_rows_before_binding(self):\n        vault = self.populated()\n        db_path = vault / 'runtime' / 'notebook.sqlite3'\n        with sqlite3.connect(db_path) as db:\n            db.execute('DROP TABLE runtime_meta')\n            db.commit()\n        book = Notebook(vault)\n        try:\n            self.assertTrue(book.db.execute(\n                \"SELECT value FROM runtime_meta WHERE key='integrity_key_id'\").fetchone()[0].startswith(KEY_ID_PREFIX))\n        finally:\n            book.close()\n        with sqlite3.connect(db_path) as db:\n            db.execute('DROP TABLE runtime_meta')\n            db.commit()\n        key_path = vault / 'runtime' / 'integrity.key'\n        key_path.write_bytes(b'Y' * KEY_BYTES)\n        os.chmod(key_path, 0o600)\n        with self.assertRaisesRegex(IntegrityKeyError, 'does not match existing protected transcript'):\n            Notebook(vault)\n"
new = "    def test_legacy_metadata_migration_validates_hmac_rows_before_binding(self):\n        import hashlib\n        import hmac\n\n        def make_legacy(name, key):\n            vault = self.root / name\n            runtime = vault / 'runtime'\n            runtime.mkdir(parents=True, mode=0o700)\n            key_path = runtime / 'integrity.key'\n            key_path.write_bytes(key)\n            os.chmod(key_path, 0o600)\n            db_path = runtime / 'notebook.sqlite3'\n            with sqlite3.connect(db_path) as db:\n                db.executescript(\"\"\"\n                    CREATE TABLE identities(\n                      hcid TEXT PRIMARY KEY, owner TEXT NOT NULL, page TEXT UNIQUE NOT NULL,\n                      binding TEXT NOT NULL, opening_hash TEXT NOT NULL, created TEXT NOT NULL);\n                    CREATE TABLE transactions(\n                      tx TEXT PRIMARY KEY, hcid TEXT NOT NULL REFERENCES identities(hcid),\n                      input TEXT NOT NULL, status TEXT NOT NULL, created TEXT NOT NULL);\n                    CREATE TABLE transcript(\n                      seq INTEGER PRIMARY KEY AUTOINCREMENT, tx TEXT NOT NULL REFERENCES transactions(tx),\n                      ordinal INTEGER NOT NULL, role TEXT NOT NULL, text TEXT NOT NULL,\n                      sha256 TEXT NOT NULL, created TEXT NOT NULL, UNIQUE(tx,ordinal));\n                \"\"\")\n                text = 'protected human text'\n                digest = 'hmac-sha256:' + hmac.new(key, text.encode('utf-8'), hashlib.sha256).hexdigest()\n                db.execute('INSERT INTO identities VALUES(?,?,?,?,?,?)',\n                           ('hcid', 'Jon', 'page', 'VERIFIED', 'legacy-opening', 'legacy-time'))\n                db.execute('INSERT INTO transactions VALUES(?,?,?,?,?)',\n                           ('tx', 'hcid', text, 'STARTED', 'legacy-time'))\n                db.execute('INSERT INTO transcript(tx,ordinal,role,text,sha256,created) VALUES(?,?,?,?,?,?)',\n                           ('tx', 0, 'HUMAN', text, digest, 'legacy-time'))\n            return vault\n\n        key = b'K' * KEY_BYTES\n        vault = make_legacy('legacy-valid', key)\n        book = Notebook(vault)\n        try:\n            self.assertTrue(book.db.execute(\n                \"SELECT value FROM runtime_meta WHERE key='integrity_key_id'\").fetchone()[0].startswith(KEY_ID_PREFIX))\n            book.project()\n            self.assertTrue(book.verify())\n        finally:\n            book.close()\n\n        wrong = make_legacy('legacy-wrong', key)\n        key_path = wrong / 'runtime' / 'integrity.key'\n        key_path.write_bytes(b'Y' * KEY_BYTES)\n        os.chmod(key_path, 0o600)\n        with self.assertRaisesRegex(IntegrityKeyError, 'does not match existing protected transcript'):\n            Notebook(wrong)\n"
if text.count(old) != 1:
    raise RuntimeError('legacy metadata migration test anchor missing or ambiguous')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
print('legacy key migration test adjusted for record-envelope era')
